version: '3.8'

services:
  # The Database (Postgres)
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aidata_db
    ports:
      - "54326:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # The Queue Broker (Redis)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: